# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoMirror',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='todo_app.Todo')),
                ('mdescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='todo_app.Todo')),
                ('mname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='todo_app.Todo')),
            ],
            options={
                'db_table': 'TodoMirror',
                'managed': True,
            },
        ),
    ]
