# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todomirror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(db_column='Description', unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(db_column='Name', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='todomirror',
            name='mdescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='todo_app.Todo', to_field='description'),
        ),
        migrations.AlterField(
            model_name='todomirror',
            name='mname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='todo_app.Todo', to_field='name'),
        ),
    ]
