# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20180215_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomirror',
            name='mdescription',
        ),
        migrations.RemoveField(
            model_name='todomirror',
            name='mname',
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(db_column='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(db_column='Name', max_length=256),
        ),
    ]
