# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20180215_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomirror',
            name='mdescription',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='todomirror',
            name='mname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(db_column='Description', max_length=150),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(db_column='Name', max_length=50),
        ),
    ]
