# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_auto_20180216_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomirror',
            name='mdescription',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='todomirror',
            name='mname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
